Simple-Extraction-Demo-Track/core/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('extraction.urls')),
]

if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

Simple-Extraction-Demo-Track/extraction/api/urls.py
from django.urls import path

from extraction.api.views import UploadedDocumentList

urlpatterns = [
    path('uploaded-documents/', UploadedDocumentList.as_view()),
]

Simple-Extraction-Demo-Track/extraction/urls.py
from django.urls import path, include

from extraction.views import ExtractionView, UploadDocumentView, get_tc_extract, ApplicationView, \
    apply_tc_to_data_extract, TCExtractListView

app_name = 'extraction'

urlpatterns = [
    path('create-extraction/<int:pk>/<str:email>/', ExtractionView.as_view(), name='create_extraction'),
    path('application/', ApplicationView.as_view(), name='application'),
    path('tc-extract-list/', TCExtractListView.as_view(), name='tc_extract_list'),
    path('get-tc-extract/<int:pk>/', get_tc_extract, name='get_tc_extract'),
    path('data-extract-tc/<int:pk>/', apply_tc_to_data_extract, name='tc_extract_data'),
    path('', UploadDocumentView.as_view(), name='upload_document'),

    # api urls
    path('api/v1/', include('extraction.api.urls')),
]

Simple-Extraction-Demo-Track/extraction/models.py
from django.db import models


class UploadedDocument(models.Model):
    name = models.CharField(max_length=255, blank=True)
    document = models.FileField(upload_to='documents/')
    file_type = models.CharField(max_length=255, blank=True)
    created_at = models.DateTimeField(auto_now_add=True)
    updated = models.DateTimeField(auto_now=True)

    def __str__(self):
        return self.name


class ExtractedDataAbstract(models.Model):
    document = models.ForeignKey(UploadedDocument, on_delete=models.CASCADE)
    surname = models.CharField(max_length=255, blank=True)
    given_name = models.CharField(max_length=255, blank=True)
    nationality = models.CharField(max_length=255, blank=True)
    issue_date = models.DateField()
    expiry_date = models.DateField()
    created_at = models.DateTimeField(auto_now_add=True)
    updated = models.DateTimeField(auto_now=True)

    def __str__(self):
        return f"{str(self.surname)}-{str(self.given_name)}-{str(self.nationality)}"

    class Meta:
        abstract = True


class ExtractedData(ExtractedDataAbstract):
    mto_id = models.CharField(max_length=255, blank=True)


class TCExtract(ExtractedDataAbstract):
    pass

Simple-Extraction-Demo-Track/extraction/forms.py
from django import forms
from django.forms import ModelForm, Form

from extraction.models import ExtractedData, UploadedDocument


class ExtractionForm(ModelForm):
    class Meta:
        model = ExtractedData
        exclude = ['created_at', 'updated', 'mto_id', 'document']


class UploadDocumentForm(ModelForm):
    class Meta:
        model = UploadedDocument
        fields = ['name', 'document']


class SendEmailForm(Form):
    """
    Form for sending an email after the extraction is completed.
    """
    email = forms.EmailField()
    subject = forms.CharField(max_length=255)
    cc = forms.EmailField()
    document = forms.FileField()
    surname = forms.CharField(max_length=255, required=False)
    given_name = forms.CharField(max_length=255, required=False)
    nationality = forms.CharField(max_length=255, required=False)
    issue_date = forms.DateField()
    expiry_date = forms.DateField()

Simple-Extraction-Demo-Track/extraction/api/views.py
from rest_framework.generics import ListAPIView

from extraction.api.serializers import UploadedDocumentSerializer
from extraction.models import UploadedDocument


class UploadedDocumentList(ListAPIView):
    """
    List all uploaded documents.
    """
    queryset = UploadedDocument.objects.all()
    serializer_class = UploadedDocumentSerializer

Simple-Extraction-Demo-Track/extraction/views.py
import os

from django.contrib import messages
from django.contrib.messages.views import SuccessMessageMixin
from django.http import JsonResponse
from django.shortcuts import render, get_object_or_404
from django.views import View
from django.views.generic import CreateView, ListView

from extraction.forms import ExtractionForm, UploadDocumentForm, SendEmailForm
from extraction.helpers import send_email_, apply_tc_to_data_extract
from extraction.models import ExtractedData, UploadedDocument, TCExtract


class ExtractionView(SuccessMessageMixin, CreateView):
    """
    Extracts data from uploaded document and saves it to the database.
    triggers perform TC Extract function if 3 or more data fields are extracted for the same document.
    """
    model = ExtractedData
    template_name = 'extraction/created_extraction.html'
    form_class = ExtractionForm
    success_url = '/'
    success_message = 'Extraction created successfully'

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['document'] = get_object_or_404(UploadedDocument, pk=self.kwargs['pk'])
        return context

    def form_valid(self, form):
        instance = form.save(commit=False)
        instance.document = get_object_or_404(UploadedDocument, pk=self.kwargs['pk'])
        instance.mto_id = self.kwargs.get('email')
        instance.save()
        if ExtractedData.objects.filter(document=instance.document).count() >= 3:
            # applying TC Extract
            apply_tc_to_data_extract(instance.document.pk)
        return super().form_valid(form)


class UploadDocumentView(SuccessMessageMixin, CreateView):
    """
    Uploading a document and sending an email to MTOs
    """
    model = UploadedDocument
    template_name = 'extraction/upload_document.html'
    form_class = UploadDocumentForm
    success_message = 'Document Uploaded successfully'

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['uploaded_documents'] = UploadedDocument.objects.all().order_by('-created_at')
        return context

    def form_valid(self, form):
        instance = form.save(commit=False)
        document = form.cleaned_data.get('document')
        instance.name = os.path.splitext(f"{document.name}")[0]
        instance.file_type = os.path.splitext(f"{document.name}")[1].replace(".", "")
        instance.save()
        return JsonResponse({'success': True})


def get_tc_extract(request, pk):
    """
    Getting TC Extract for a document and using it to supply initial data for SendEmailForm
    :param request:
    :param pk:
    :return:
    """
    tc_extract = get_object_or_404(TCExtract, pk=pk)
    initial_data = {'surname': tc_extract.surname, 'given_name': tc_extract.given_name,
                    'nationality': tc_extract.nationality, "document": tc_extract.document.document,
                    'issue_date': tc_extract.issue_date, 'expiry_date': tc_extract.expiry_date,
                    'email': 'track20@varaluae.com',
                    }
    form = SendEmailForm(initial=initial_data)
    return render(request, 'extraction/tc_extract.html', {'form': form, 'tc_extract': tc_extract})


class ApplicationView(View):
    """
    Gets all the TC Extracts and sends an email to the emails from SendEmailForm
    """
    template_name = 'extraction/application.html'

    def get(self, request):
        tc_extracts = TCExtract.objects.select_related('document').all().order_by('-created_at')
        return render(request, self.template_name, {'tc_extracts': tc_extracts})

    def post(self, request):
        email = request.POST.get('email')
        cc = request.POST.get('cc')
        subject = request.POST.get('subject')
        tc_id = request.POST.get('tc_id')
        tc_extract = get_object_or_404(TCExtract, pk=tc_id)
        email_template = 'extraction/email/application_email.html'
        send_email_(subject=subject, to_email=[email], data=tc_extract, email_template=email_template,
                    attachment=tc_extract.document.document, cc=[cc])
        messages.success(request, 'Application sent successfully')
        tc_extracts = TCExtract.objects.all().order_by('-created_at')
        return render(request, self.template_name, {'tc_extracts': tc_extracts})


class TCExtractListView(ListView):
    """
    List of all TC Extracts
    """
    model = TCExtract
    template_name = 'extraction/tc_extract_list.html'
    queryset = TCExtract.objects.select_related("document").all().order_by('-created_at')

Simple-Extraction-Demo-Track/templates/base.html
<!doctype html>
<html lang="en">

<head>
  {% load static %}
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <title>{% block title %}Data Extraction {% endblock %}</title>
  <!-- Font Awesome -->
  <link href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.0.0/css/all.min.css" rel="stylesheet" />
  <!-- Google Fonts -->
  <link href="https://fonts.googleapis.com/css?family=Roboto:300,400,500,700&display=swap" rel="stylesheet" />
  <!-- MDB -->
  <link href="https://cdnjs.cloudflare.com/ajax/libs/mdb-ui-kit/4.4.0/mdb.min.css" rel="stylesheet" />
  <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.2.0/dist/css/bootstrap.min.css" rel="stylesheet"
    integrity="sha384-gH2yIJqKdNHPEq0n4Mqa/HGKIhSkIHeL5AyhkYV8i59U5AR6csBvApHHNl/vI1Bx" crossorigin="anonymous">
  <link rel="stylesheet" href="{% static 'css/style.css'%}" />
  <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/izitoast/1.4.0/css/iziToast.min.css">
  {% block styles %}{% endblock %}
</head>

<body>
  {% block navbar %}{% include "includes/navbar.html" %}{% endblock%}
  <!-- <div id="loader-wrapper">
    <div id="loader"></div>

    <div class="loader-section section-left"></div>
    <div class="loader-section section-right"></div>

  </div> -->
  <div class="container p-4">
    {% block content %}{% endblock %}
  </div>
  {% block footer %}{% include "includes/footer.html" %}{% endblock%}
  <!-- MDB -->
  <script src="//code.jquery.com/jquery.min.js"></script>
  <script type="text/javascript" src="https://cdnjs.cloudflare.com/ajax/libs/mdb-ui-kit/4.4.0/mdb.min.js"></script>
  <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.2.0/dist/js/bootstrap.bundle.min.js"
    integrity="sha384-A3rJD856KowSb7dwlZdYEkO39Gagi7vIsF0jrRAoQmDKKtQBHUuLZ9AsSv4jD4Xa" crossorigin="anonymous">
  </script>
  <script src="https://cdnjs.cloudflare.com/ajax/libs/izitoast/1.4.0/js/iziToast.min.js"></script>
  <script src="{% static 'js/app.js' %}"></script>
  {% include 'includes/messages.html' with messages=messages %}
  {% block scripts %}{% endblock %}
</body>

</html>

Simple-Extraction-Demo-Track/templates/extraction/application.html
{% extends 'base.html' %}
{% load static %}
{% block content %}
<div class="row mt-5 shadow p-5 rounded">
    <div class="col-12 mb-3">
        <p class="h1 text-primary text-center">Application Form</p>
    </div>
    <div class="col-12 col-md-2 col-lg-2">
        <p class="lead text-primary">Service ID</p>
    </div>
    <div class="col-12 col-md-10 col-lg-10">
        <select name="extract" class="js-searchBox form-control w-100" id="extract-id">
            <option value="">Select Service ID</option>
            {% for extract in tc_extracts %}
            <option value="{{ extract.pk }}">{{ extract.document.pk }}</option>
            {% endfor %}
        </select>
    </div>
    <div class="col-12 mt-3">
        <button href="#" class="btn btn-primary btn-lg w-100" data-mdb-toggle="modal"
            data-mdb-target="#email-sending-form" id="email-form-auto-fill">Auto Fill</a>
    </div>

    <!-- Modal -->
    <div class="modal fade" id="email-sending-form" tabindex="-1" aria-labelledby="exampleModalLabel"
        aria-hidden="true">
        <div class="modal-dialog modal-xl">
            <div class="modal-content p-3">
                <div class="modal-header">
                    <h5 class="modal-title text-primary" id="exampleModalLabel">Application Form</h5>
                    <button type="button" class="btn-close" data-mdb-dismiss="modal" aria-label="Close"></button>
                </div>
                <div class="modal-body" id="email-form"></div>
                <!-- <div class="modal-footer">
                    <button type="button" class="btn btn-secondary" data-mdb-dismiss="modal">Close</button>
                    <button type="button" class="btn btn-primary">Save changes</button>
                </div> -->
            </div>
        </div>
    </div>
</div>
{% endblock %}
{% block scripts %}
<script src="{% static 'dist/js/jquery-searchbox.js' %}"></script>
<script>
    $('.js-searchBox').searchBox();
    $('.formTextbox').addClass('shadow form-control')
    $('.formTextbox').removeAttr('style')
    $('#email-form-auto-fill').on('click', function () {
        let extract = $('#extract-id').val()
        $.ajax({
            url: `/get-tc-extract/${extract}`,
            type: "get",
            dataType: 'json',
            success: function (data) {
                console.log("Success" + data)
                iziToast.info({
                    title: "info",
                    message: data['message'],
                    position: 'topRight'
                });
                // $('email-form').html(data.responseText);
            },
            error: function (data) {
                console.log(data)
                console.log(data.responseText)
                if (extract) {
                    $('#email-form').html(data.responseText)
                } else {
                    iziToast.info({
                        title: "info",
                        message: "Please select extract first",
                        position: 'topRight'
                    });
                    $('#email-form').html(`
                    <div class="alert alert-danger alert-dismissible fade show" role="alert">
                        <strong>Attention!</strong> Please select a document in the dropdown before clicking autofill.
                        <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
                    </div>
                    `)
                }
            }
        })
    })
</script>
{% endblock %}

Simple-Extraction-Demo-Track/templates/extraction/created_extraction.html
{% extends 'base.html' %}
{% load static %}
{% comment %} {% block navbar %}{% endblock%} {% endcomment %}
{% block content %}
<div class="row">
    <p class="h1 text-primary">Extract Data</p>
    <div class="col-12 col-md-4 col-lg-4 shadow p-5 mt-5 rounded">
        <p class="lead text-primary">Preview {{ document.file_type }} </p>
        {% if document.file_type  == "pdf" %}
        <div id="pdf-viewer"></div>
        <div data-url="{{ document.document.url }}" id="pdf-url"></div>
        {% elif document.file_type  == "docx" or document.file_type  == "doc"%}
        <iframe src="https://docs.google.com/gview?url={{ document.document.url }}&embedded=true"></iframe>
        {% else %}
        <img src="{{ document.document.url }}" class="img-fluid" />
        {% endif %}
    </div>
    <div class="col-12 col-md-8 col-lg-8 shadow p-5 mt-5 rounded">
        <form method="post" action="." enctype="multipart/form-data">
            {% csrf_token %}
            {% include 'includes/form.html' with form=form %}
            <div class="d-flex justify-content-center">
                <button type="submit" class="btn btn-primary btn-lg shadow">Send</button>
            </div>
        </form>
    </div>
</div>
{% endblock %}
{% block scripts %}
<script src="https://cdn.jsdelivr.net/npm/pdfobject@2.2.8/pdfobject.min.js"></script>
<script>
    let pdfFile = $('#pdf-url').attr('data-url');
    PDFObject.embed(pdfFile, "#pdf-viewer");
</script>
{% endblock %}

Simple-Extraction-Demo-Track/templates/extraction/tc_extract.html
<form action="{% url 'extraction:application' %}" method="post">
  {% csrf_token %}
  {% include 'includes/form.html' %}
  <input type="hidden" name="tc_id" value="{{ tc_extract.id }}" />
  <div class="d-flex justify-content-center">
    <button class="btn btn-primary shadow btn-lg" type="submit">Send</button>
  </div>
</form>

Simple-Extraction-Demo-Track/templates/extraction/tc_extract_list.html
{% extends 'base.html' %}
{% load static %}
{% block styles %}
<link rel="stylesheet" type="text/css" href="https://cdn.datatables.net/1.12.1/css/jquery.dataTables.css">

{% endblock %}
{% block content %}

<div class="row mt-5">
  <p class="h1 text-center text-primary mb-3">TC Extracts</p>
  <div class="col-12 shadow mt-5 p-5 rounded table table-responsive" id="desktop-table">
    <table id="table_id" class="display">
      <thead class="bg-primary text-white">
        <tr>
          <th>S/no</th>
          <th>Document</th>
          <th>Service ID</th>
          <th>Surname</th>
          <th>Given Name</th>
          <th>Nationality</th>
          <th>Issue Date</th>
          <th>Expiry Date</th>
          <th></th>
        </tr>
      </thead>
      <tbody>
        {% for object in object_list %}
        <tr>
          <td>{{ forloop.counter }}</td>
          <td>
            <a class="btn btn-link btn-sm" href="{{ object.document.document.url }}" target="_blank">
              <i class="fa-regular fa-file-pdf fa-3x"></i>
            </a>
          </td>
          <td>{{ object.document.pk }}</td>
          <td>{{ object.surname }}</td>
          <td>{{ object.given_name }}</td>
          <td>{{ object.nationality }}</td>
          <td>{{ object.issue_date }}</td>
          <td>{{ object.expiry_date }}</td>
          <td>
            <div class="btn-group">
              <button class="btn btn-link btn-sm dropdown-toggle" type="button" data-mdb-toggle="dropdown"
                aria-expanded="false">
              </button>

              <ul class="dropdown-menu">
                <li><a class="dropdown-item" href="#">Delete</a>
                </li>
              </ul>
            </div>
          </td>
        </tr>
        {% endfor %}
      </tbody>
    </table>
  </div>
  <div class="col-12 shadow rounded p-4 mt-3 table table-responsive" id="mobile-table">
    <table class="table">
      <thead class="bg-primary text-white">
        <tr>
          <th>S/no</th>
          <th>Document</th>
          <th>Service ID</th>
          <th>Surname</th>
          <th>Given Name</th>
          <th>Nationality</th>
          <th>Issue Date</th>
          <th>Expiry Date</th>
          <th></th>
        </tr>
      </thead>
      <tbody>
        {% for object in object_list %}
        <tr>
          <td>{{ forloop.counter }}</td>
          <td>
            <a class="btn btn-link btn-sm" href="{{ object.document.document.url }}" target="_blank">
              <i class="fa-regular fa-file-pdf fa-3x"></i>
            </a>
          </td>
          <td>{{ object.document.pk }}</td>
          <td>{{ object.surname }}</td>
          <td>{{ object.given_name }}</td>
          <td>{{ object.nationality }}</td>
          <td>{{ object.issue_date|date:"Y-m-d" }}</td>
          <td>{{ object.expiry_date|date:"Y-m-d" }}</td>
          <td>
            <div class="btn-group">
              <button class="btn btn-link btn-sm dropdown-toggle" type="button" data-mdb-toggle="dropdown"
                aria-expanded="false">
              </button>

              <ul class="dropdown-menu">
                <li><a class="dropdown-item" href="#">Delete</a>
                </li>
              </ul>
            </div>
          </td>
        </tr>
        {% endfor %}
      </tbody>
    </table>
  </div>
</div>

{% endblock %}
{% block scripts %}
<script type="text/javascript" charset="utf8" src="https://cdn.datatables.net/1.12.1/js/jquery.dataTables.js"></script>
<script src="{% static 'js/table.js' %}"></script>
{% endblock %}

Simple-Extraction-Demo-Track/templates/extraction/upload_document.html
{% extends 'base.html' %}
{% load static %}
{% block styles %}
<link rel="stylesheet" href="{% static 'fancy-file-uploader/fancy_fileupload.css' %}">
<link rel="stylesheet" type="text/css" href="https://cdn.datatables.net/1.12.1/css/jquery.dataTables.css">

{% endblock %}
{% block content %}

<div class="row mt-5">
  <p class="h1 text-center text-primary mb-3">Upload Document</p>
  <div class="col-12">
    <input type="file" id="multiple-documents-upload" name="document"
      accept=".pdf, .jpg, .JPG, .png , .PNG, .jpeg, .JPEG">
    <div class="d-flex justify-content-end">
      <p class="text-muted">(supported file formats .pdf, .jpg, .JPG, .png , .PNG, .jpeg, .JPEG)</p>
    </div>
  </div>
  <div class="col-12 shadow mt-5 p-5 rounded table table-responsive" id="desktop-table">
    <table id="table_id" class="display">
      <thead class="bg-primary text-white">
        <tr>
          <th>S/no</th>
          <th>Document Name</th>
          <th>File type</th>
          <th>Date</th>
          <th>view</th>
          <th></th>
        </tr>
      </thead>
      <tbody>
        {% for document in uploaded_documents %}
        <tr>
          <td>{{ forloop.counter }}</td>
          <td>{{ document.name }}</td>
          <td>{{ document.file_type }}</td>
          <td>{{ document.created_at }}</td>
          <td>
            <a class="btn btn-link btn-sm" href="{{ document.document.url }}" target="_blank">
              <i class="fa-regular fa-file-pdf fa-3x"></i>
            </a>
          </td>
          <td>
            <div class="btn-group">
              <button class="btn btn-link btn-sm dropdown-toggle" type="button" data-mdb-toggle="dropdown"
                aria-expanded="false">
              </button>

              <ul class="dropdown-menu">
                <li><a class="dropdown-item" href="#">Delete</a>
                </li>
              </ul>
            </div>
          </td>
        </tr>
        {% endfor %}
      </tbody>
    </table>
  </div>
  <div class="col-12 shadow rounded p-4 mt-3 table table-responsive" id="mobile-table">
    <table class="table">
      <thead class="bg-primary text-white">
        <tr>
          <th>no</th>
          <th>Name</th>
          <th>type</th>
          <th>Date</th>
          <th>view</th>
          <th></th>
        </tr>
      </thead>
      <tbody>
        {% for document in uploaded_documents %}
        <tr>
          <td>{{ forloop.counter }}</td>
          <td>{{ document.name }}</td>
          <td>{{ document.file_type }}</td>
          <td>{{ document.created_at|date:"Y-m-d" }}</td>
          <td>
            <a class="btn btn-link btn-sm" href="{{ document.document.url }}" target="_blank">
              <i class="fa-regular fa-file-pdf fa-2x"></i>
            </a>
          </td>
          <td>
            <div class="btn-group">
              <button class="btn btn-link btn-sm dropdown-toggle" type="button" data-mdb-toggle="dropdown"
                aria-expanded="false">
              </button>

              <ul class="dropdown-menu">
                <li><a class="dropdown-item" href="#">Delete</a>
                </li>
              </ul>
            </div>
          </td>
        </tr>
        {% endfor %}
      </tbody>
    </table>
  </div>
</div>

{% endblock %}
{% block scripts %}
<script src="{% static 'fancy-file-uploader/jquery.ui.widget.js' %}"></script>
<script src="{% static 'fancy-file-uploader/jquery.fileupload.js' %}"></script>
<script src="{% static 'fancy-file-uploader/jquery.iframe-transport.js' %}"></script>
<script src="{% static 'fancy-file-uploader/jquery.fancy-fileupload.js' %}"></script>
<script src="{% static 'fancy-file-uploader/fancy_fileupload.js' %}"></script>
<script type="text/javascript" charset="utf8" src="https://cdn.datatables.net/1.12.1/js/jquery.dataTables.js"></script>
<script src="{% static 'js/table.js' %}"></script>
<script type="text/javascript">
  $(function () {
    $('#multiple-documents-upload').FancyFileUpload({
      'url': '/',
      params: {
        action: 'fileuploader',
        "csrfmiddlewaretoken": "{{ csrf_token }}",
      },
    });
  });
</script>
{% endblock %}

Simple-Extraction-Demo-Track/templates/includes/form.html
{% load widget_tweaks %}

{% for field in form %}
<div class="row mb-3">
    <div class="col-12 col-md-2 col-lg-2">
        <label class="text-primary">{{field.label}}</label>
    </div>
    <div class="col-12 col-md-10 col-lg-10">
        {% if "date" in field.label %}
            {% render_field field class+="form-control shadow rounded" placeholder=field.label type="date" %}
        {% else %}
            {% render_field field class+="form-control shadow rounded" placeholder=field.label %}
        {% endif %}
    </div>
    <div class="text-danger">{{field.errors}}</div>
</div>
{% endfor %}

Simple-Extraction-Demo-Track/templates/includes/messages.html
{% for message in messages %}
    <script>
        let message = "{{message}}"
        let message_tag = "{{message.tags}}"
        console.log(message)
        if (message_tag === "success" ){
          iziToast.success({
            title: "Success",
            message: message,
            position: 'topRight'
          });
         }
        if (message_tag === "info" ){
          iziToast.info({
            title: "Info",
            message: message,
            position: 'topRight'
          });
         }
         if (message_tag === "error" ){
          iziToast.error({
            title: "Error",
            message: message,
            position: 'topRight'
          });
         }
    </script>
{% endfor %}

Simple-Extraction-Demo-Track/templates/includes/navbar.html
{% load static %}
<!-- Navbar -->
<nav class="navbar navbar-expand-lg navbar-dark bg-dark shadow text-white">
  <!-- Container wrapper -->
  <div class="container-fluid">
    <!-- Toggle button -->
    <button class="navbar-toggler" type="button" data-mdb-toggle="collapse" data-mdb-target="#navbarSupportedContent"
      aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
      <i class="fas fa-bars"></i>
    </button>

    <!-- Collapsible wrapper -->
    <div class="collapse navbar-collapse" id="navbarSupportedContent">
      <!-- Navbar brand -->
      <a class="navbar-brand mt-2 mt-lg-0" href="/">
        <img src="{% static 'img/logo.png' %}" height="50" alt="MDB Logo" loading="lazy" />
      </a>
      <!-- Left links -->
      <ul class="navbar-nav me-auto mb-2 mb-lg-0">
        <li class="nav-item">
          <a class="nav-link lead" href="/">Upload Document</a>
        </li>
        <li class="nav-item">
          <a class="nav-link" href="{% url 'extraction:application' %}">Application</a>
        </li>
        <li class="nav-item">
          <a class="nav-link" href="{% url 'extraction:tc_extract_list' %}">TC Extracts</a>
        </li>
      </ul>
      <!-- Left links -->
    </div>
    <!-- Collapsible wrapper -->
    <!-- Right elements -->
    <div class="d-flex align-items-center">
      <div class="dropdown">
        <a class="dropdown-toggle d-flex align-items-center hidden-arrow" href="#" id="navbarDropdownMenuAvatar"
          role="button" data-mdb-toggle="dropdown" aria-expanded="false">
          <img src="https://cdn-icons-png.flaticon.com/512/149/149071.png" class="rounded-circle" height="50"
            alt="Black and White Portrait of a Man" loading="lazy" />
        </a>
        <ul class="dropdown-menu dropdown-menu-end" aria-labelledby="navbarDropdownMenuAvatar">
          <li>
            <a class="dropdown-item" href="#">My profile</a>
          </li>
          <li>
            <a class="dropdown-item" href="#">Logout</a>
          </li>
        </ul>
      </div>
    </div>
    <!-- Right elements -->
  </div>
  <!-- Container wrapper -->
</nav>